# LibreLane configuration file

DESIGN_NAME: heichips25_pudding
VERILOG_FILES:
  - dir::../src/heichips25_pudding.sv

CLOCK_PORT: clk
CLOCK_PERIOD: 10 # 10ns = 100MHz

# Reduce wasted space
TOP_MARGIN_MULT: 1
BOTTOM_MARGIN_MULT: 1
LEFT_MARGIN_MULT: 6
RIGHT_MARGIN_MULT: 6

# Absolute die size
FP_SIZING: absolute
PL_TARGET_DENSITY_PCT: 80

# Small DEF template
DIE_AREA: [0, 0, 500, 200]
FP_DEF_TEMPLATE: dir::def/heichips25_template_small.def

# Large DEF template
#DIE_AREA: [0, 0, 500, 415]
#FP_DEF_TEMPLATE: dir::def/heichips25_template_large.def

# Don't use power rings or TopMetal2 layer
PDN_MULTILAYER: false
#PDN_MULTILAYER: true
RT_MAX_LAYER: TopMetal1
#FP_PDN_VPITCH: 20
#FP_PDN_HPITCH: 20

# Enable for better SystemVerilog support
#USE_SLANG: true

# reserve space for the logo
FP_OBSTRUCTIONS:
  - [350, 30, 500, 80]
  - [350, 120, 500, 170]

MACROS:
  dac2u128out4in:
    gds:
      - dir::../gds/dac2u128out4in.gds
    lef:
      - dir::../gds/dac2u128out4in.lef
    instances:
      dacL:
        location: [360, 40]
        orientation: N
      dacH:
        location: [360, 130]
        orientation: N
